spring.application.name=GithubConnector

server.port=8086
server.servlet.contextPath=/github
spring.profiles.active=dev

# GitHub API base URL
github.api.base-url=https://api.github.com

github.token=<!!! github-token-goes-here !!!>